# Generated by Django 3.1.1 on 2020-09-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='profile_pic',
            field=models.ImageField(default="{% static 'defaultui' %}", upload_to='profilepics/'),
        ),
    ]
